### ISSUE TITLE
Add MC account verification function

### ISSUE THREAD

**Issue by crystall1nedev** [PojavLauncherTeam/PojavBot#52]
We need to improve the way we verify user accounts in the Discord server. Preferably, use the bot to sign into Microsoft and see if there is a valid MC account attached.

**Comment by Uni0005** [comment]
okay I'll try to do this

**Comment by crystall1nedev** [comment]
@Uni0005 Helpful information for interacting with MS account login:
https://wiki.vg/Microsoft_Authentication_Scheme#Checking_Game_Ownership
